// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("XrmMockupTest")]
[assembly: AssemblyProductAttribute("XrmMockup")]
[assembly: AssemblyDescriptionAttribute("A tool for mocking a MS CRM instance when unit testing")]
[assembly: AssemblyVersionAttribute("0.2.28")]
[assembly: AssemblyFileVersionAttribute("0.2.28")]
[assembly: AssemblyCompanyAttribute("Delegate A/S")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "XrmMockupTest";
        internal const System.String AssemblyProduct = "XrmMockup";
        internal const System.String AssemblyDescription = "A tool for mocking a MS CRM instance when unit testing";
        internal const System.String AssemblyVersion = "0.2.28";
        internal const System.String AssemblyFileVersion = "0.2.28";
        internal const System.String AssemblyCompany = "Delegate A/S";
    }
}
