// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("XrmMockup2013")]
[assembly: AssemblyProductAttribute("XrmMockup")]
[assembly: AssemblyDescriptionAttribute("A simulation engine that can mock a specific MS CRM instance. Useful for testing and debugging business logic.")]
[assembly: AssemblyVersionAttribute("0.13.1")]
[assembly: AssemblyFileVersionAttribute("0.13.1")]
[assembly: AssemblyCompanyAttribute("Delegate A/S")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "XrmMockup2013";
        internal const System.String AssemblyProduct = "XrmMockup";
        internal const System.String AssemblyDescription = "A simulation engine that can mock a specific MS CRM instance. Useful for testing and debugging business logic.";
        internal const System.String AssemblyVersion = "0.13.1";
        internal const System.String AssemblyFileVersion = "0.13.1";
        internal const System.String AssemblyCompany = "Delegate A/S";
    }
}
