//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Delegate XrmContext v3.0.1.
//
//     Generated from the live org https://orgd3a12bfa.crm4.dynamics.com scoped to the
//     'template' entity. The main XrmContext.cs is generated from a different reference org
//     that does not contain 'template', so this type is generated separately and kept here.
//
//     Adjusted to match the existing XrmContext.cs style (which predates v3): the cosmetic
//     [DisplayName]/[MaxLength]/[Range] annotations and their System.ComponentModel* usings were
//     removed (net462 does not reference DataAnnotations and the existing context omits them),
//     and the unused standalone Template_TemplateTypeCode option-set enum was dropped because
//     'templatetypecode' is an EntityName (string). The attribute data is otherwise unchanged.
//     The 'componentstate' enum referenced below is defined in XrmContext.cs.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace DG.XrmFramework.BusinessDomain.ServiceContext {


    /// <summary>
    /// <para>Template for an email message that contains the standard attributes of an email message.</para>
    /// <para>Display Name: Email Template</para>
    /// </summary>
    [EntityLogicalName("template")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class Template : ExtendedEntity<EmptyEnum, EmptyEnum> {

        public const string EntityLogicalName = "template";

        public const int EntityTypeCode = 2010;

        public Template() :
                base(EntityLogicalName) {
        }

        public Template(Guid Id) :
                base(EntityLogicalName, Id) {
        }

        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("title");
            }
        }

        [AttributeLogicalName("templateid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("templateid", value);
            }
        }

        /// <summary>
        /// <para>Unique identifier of the template.</para>
        /// </summary>
        [AttributeLogicalName("templateid")]
        public Guid? TemplateId {
            get {
                return GetAttributeValue<Guid?>("templateid");
            }
            set {
                SetId("templateid", value);
            }
        }

        /// <summary>
        /// <para>Body text of the email template.</para>
        /// </summary>
        [AttributeLogicalName("body")]
        public string Body {
            get {
                return GetAttributeValue<string>("body");
            }
            set {
                SetAttributeValue("body", value);
            }
        }

        /// <summary>
        /// <para>For internal use only.</para>
        /// </summary>
        [AttributeLogicalName("componentstate")]
        public componentstate? ComponentState {
            get {
                return GetOptionSetValue<componentstate>("componentstate");
            }
        }

        /// <summary>
        /// <para>Unique identifier of the user who created the email template.</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }

        /// <summary>
        /// <para>Date and time when the email template was created.</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }

        /// <summary>
        /// <para>Unique identifier of the delegate user who created the template.</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// <para>Description of the email template.</para>
        /// </summary>
        [AttributeLogicalName("description")]
        public string Description {
            get {
                return GetAttributeValue<string>("description");
            }
            set {
                SetAttributeValue("description", value);
            }
        }

        [AttributeLogicalName("entityimageid")]
        public Guid? EntityImageId {
            get {
                return GetAttributeValue<Guid?>("entityimageid");
            }
        }

        /// <summary>
        /// <para>For internal use only.</para>
        /// </summary>
        [AttributeLogicalName("generationtypecode")]
        public int? GenerationTypeCode {
            get {
                return GetAttributeValue<int?>("generationtypecode");
            }
            set {
                SetAttributeValue("generationtypecode", value);
            }
        }

        /// <summary>
        /// <para>Unique identifier of the data import or data migration that created this record.</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        public int? ImportSequenceNumber {
            get {
                return GetAttributeValue<int?>("importsequencenumber");
            }
            set {
                SetAttributeValue("importsequencenumber", value);
            }
        }

        /// <summary>
        /// <para>Version in which the form is introduced.</para>
        /// </summary>
        [AttributeLogicalName("introducedversion")]
        public string IntroducedVersion {
            get {
                return GetAttributeValue<string>("introducedversion");
            }
            set {
                SetAttributeValue("introducedversion", value);
            }
        }

        /// <summary>
        /// <para>Information that specifies whether this component can be customized.</para>
        /// </summary>
        [AttributeLogicalName("iscustomizable")]
        public BooleanManagedProperty IsCustomizable {
            get {
                return GetAttributeValue<BooleanManagedProperty>("iscustomizable");
            }
            set {
                SetAttributeValue("iscustomizable", value);
            }
        }

        /// <summary>
        /// <para>Indicates whether the solution component is part of a managed solution.</para>
        /// </summary>
        [AttributeLogicalName("ismanaged")]
        public bool? IsManaged {
            get {
                return GetAttributeValue<bool?>("ismanaged");
            }
        }

        /// <summary>
        /// <para>Information about whether the template is personal or is available to all users.</para>
        /// </summary>
        [AttributeLogicalName("ispersonal")]
        public bool? IsPersonal {
            get {
                return GetAttributeValue<bool?>("ispersonal");
            }
            set {
                SetAttributeValue("ispersonal", value);
            }
        }

        /// <summary>
        /// <para>Indicates if a template is recommended by Dynamics 365.</para>
        /// </summary>
        [AttributeLogicalName("isrecommended")]
        public bool? IsRecommended {
            get {
                return GetAttributeValue<bool?>("isrecommended");
            }
        }

        /// <summary>
        /// <para>Language of the email template.</para>
        /// </summary>
        [AttributeLogicalName("languagecode")]
        public int? LanguageCode {
            get {
                return GetAttributeValue<int?>("languagecode");
            }
            set {
                SetAttributeValue("languagecode", value);
            }
        }

        /// <summary>
        /// <para>MIME type of the email template.</para>
        /// </summary>
        [AttributeLogicalName("mimetype")]
        public string MimeType {
            get {
                return GetAttributeValue<string>("mimetype");
            }
            set {
                SetAttributeValue("mimetype", value);
            }
        }

        /// <summary>
        /// <para>Unique identifier of the user who last modified the template.</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// <para>Date and time when the email template was last modified.</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }

        /// <summary>
        /// <para>Unique identifier of the delegate user who last modified the template.</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// <para>For internal use only. Shows the number of times emails that use this template have been opened.</para>
        /// </summary>
        [AttributeLogicalName("opencount")]
        public int? OpenCount {
            get {
                return GetAttributeValue<int?>("opencount");
            }
        }

        /// <summary>
        /// <para>Shows the open rate of this template. This is based on number of opens on followed emails that use this template.</para>
        /// </summary>
        [AttributeLogicalName("openrate")]
        public int? OpenRate {
            get {
                return GetAttributeValue<int?>("openrate");
            }
        }

        /// <summary>
        /// <para>For internal use only.</para>
        /// </summary>
        [AttributeLogicalName("overwritetime")]
        public DateTime? OverwriteTime {
            get {
                return GetAttributeValue<DateTime?>("overwritetime");
            }
        }

        /// <summary>
        /// <para>Unique identifier of the user or team who owns the template for the email activity.</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        public EntityReference OwnerId {
            get {
                return GetAttributeValue<EntityReference>("ownerid");
            }
            set {
                SetAttributeValue("ownerid", value);
            }
        }

        /// <summary>
        /// <para>Unique identifier of the business unit that owns the template.</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        public EntityReference OwningBusinessUnit {
            get {
                return GetAttributeValue<EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// <para>Unique identifier of the team who owns the template.</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        public EntityReference OwningTeam {
            get {
                return GetAttributeValue<EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// <para>Unique identifier of the user who owns the template.</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        public EntityReference OwningUser {
            get {
                return GetAttributeValue<EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// <para>XML data for the body of the email template.</para>
        /// </summary>
        [AttributeLogicalName("presentationxml")]
        public string PresentationXml {
            get {
                return GetAttributeValue<string>("presentationxml");
            }
            set {
                SetAttributeValue("presentationxml", value);
            }
        }

        /// <summary>
        /// <para>Title of the template.</para>
        /// </summary>
        [AttributeLogicalName("title")]
        public string PrimaryNameField {
            get {
                return GetAttributeValue<string>("title");
            }
            set {
                SetAttributeValue("title", value);
            }
        }

        /// <summary>
        /// <para>For internal use only. Shows the number of times emails that use this template have received replies.</para>
        /// </summary>
        [AttributeLogicalName("replycount")]
        public int? ReplyCount {
            get {
                return GetAttributeValue<int?>("replycount");
            }
        }

        /// <summary>
        /// <para>Shows the reply rate for this template. This is based on number of replies received on followed emails that use this template.</para>
        /// </summary>
        [AttributeLogicalName("replyrate")]
        public int? ReplyRate {
            get {
                return GetAttributeValue<int?>("replyrate");
            }
        }

        /// <summary>
        /// <para>Safe html of email template.</para>
        /// </summary>
        [AttributeLogicalName("safehtml")]
        public string SafeHtml {
            get {
                return GetAttributeValue<string>("safehtml");
            }
            set {
                SetAttributeValue("safehtml", value);
            }
        }

        /// <summary>
        /// <para>Unique identifier of the associated solution.</para>
        /// </summary>
        [AttributeLogicalName("solutionid")]
        public Guid? SolutionId {
            get {
                return GetAttributeValue<Guid?>("solutionid");
            }
        }

        /// <summary>
        /// <para>Subject associated with the email template.</para>
        /// </summary>
        [AttributeLogicalName("subject")]
        public string Subject {
            get {
                return GetAttributeValue<string>("subject");
            }
            set {
                SetAttributeValue("subject", value);
            }
        }

        /// <summary>
        /// <para>XML data for the subject of the email template.</para>
        /// </summary>
        [AttributeLogicalName("subjectpresentationxml")]
        public string SubjectPresentationXml {
            get {
                return GetAttributeValue<string>("subjectpresentationxml");
            }
            set {
                SetAttributeValue("subjectpresentationxml", value);
            }
        }

        /// <summary>
        /// <para>Safe html of email template subject.</para>
        /// </summary>
        [AttributeLogicalName("subjectsafehtml")]
        public string SubjectSafeHtml {
            get {
                return GetAttributeValue<string>("subjectsafehtml");
            }
            set {
                SetAttributeValue("subjectsafehtml", value);
            }
        }

        /// <summary>
        /// <para>For internal use only.</para>
        /// </summary>
        [AttributeLogicalName("templateidunique")]
        public Guid? TemplateIdUnique {
            get {
                return GetAttributeValue<Guid?>("templateidunique");
            }
        }

        /// <summary>
        /// <para>Type of email template.</para>
        /// </summary>
        [AttributeLogicalName("templatetypecode")]
        public string TemplateTypeCode {
            get {
                return GetAttributeValue<string>("templatetypecode");
            }
            set {
                SetAttributeValue("templatetypecode", value);
            }
        }

        /// <summary>
        /// <para>Title of the template.</para>
        /// </summary>
        [AttributeLogicalName("title")]
        public string Title {
            get {
                return GetAttributeValue<string>("title");
            }
            set {
                SetAttributeValue("title", value);
            }
        }

        /// <summary>
        /// <para>Shows the number of sent emails that use this template.</para>
        /// </summary>
        [AttributeLogicalName("usedcount")]
        public int? UsedCount {
            get {
                return GetAttributeValue<int?>("usedcount");
            }
        }

        /// <summary>
        /// <para>Version number of the template.</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }

        public static Template Retrieve(IOrganizationService service, Guid id, params Expression<Func<Template,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
}
