using System;
using System.ServiceModel;
using DG.Some.Namespace;
using DG.XrmFramework.BusinessDomain.ServiceContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace DG.NotAKeyWord.SSPOnBoarding.Plugins
{
    public class BusTicketSync : PluginNonDaxif
    {
        /*
         * This is a plugin that isn't registered through DAXIF, therefore we expect that the plugin can be found registered in Metadata.xml, which is
         * generated by MetadataGenerator365. It have to generate metadata from Lab4 solutions, since some tests are dependent on stuff op there and
         * from Pre and Post-images Test Solution from the same Server. This plugin and AccountCurrencyBase are both registered here.
         */

        public override void Execute(IServiceProvider serviceProvider)
        {
            // Migrated from dg_bus / dg_bus_parental to ctx_parent / the ctx_parent_child N:N. Fires on
            // Associate/Disassociate of that relationship and stamps ctx_Amount (25 on associate, 26 on
            // disassociate) so TestAssocDissoc can verify the plugin ran on those messages.
            var context = new LocalPluginContext(serviceProvider);

            var relationship = context.PluginExecutionContext.InputParameters["Relationship"] as Relationship;
            if (relationship.SchemaName != "ctx_parent_child") return;

            if (context.PluginExecutionContext.Depth > 1) return;

            var service = context.OrganizationService;
            var id = context.PluginExecutionContext.PrimaryEntityId;

            var snapshotChild = ctx_parent.Retrieve(service, id, x => x.ctx_Amount);

            if (snapshotChild != null)
                service.Update(new ctx_parent(id)
                {
                    ctx_Amount = context.PluginExecutionContext.MessageName == "Associate" ? 25 : 26
                });
        }
    }
}
