// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("MetadataGenerator13")]
[assembly: AssemblyProductAttribute("XrmMockup")]
[assembly: AssemblyDescriptionAttribute("A simulation engine that can mock a specific MS CRM instance. Useful for testing and debugging business logic.")]
[assembly: AssemblyVersionAttribute("1.2.4")]
[assembly: AssemblyFileVersionAttribute("1.2.4")]
[assembly: AssemblyCompanyAttribute("Delegate A/S")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "MetadataGenerator13";
        internal const System.String AssemblyProduct = "XrmMockup";
        internal const System.String AssemblyDescription = "A simulation engine that can mock a specific MS CRM instance. Useful for testing and debugging business logic.";
        internal const System.String AssemblyVersion = "1.2.4";
        internal const System.String AssemblyFileVersion = "1.2.4";
        internal const System.String AssemblyCompany = "Delegate A/S";
    }
}
